"""
report.py — Output generators: Markdown, CSV, and JSON weekly reports.
"""

import csv
import json
import os
from datetime import datetime, timezone
from pathlib import Path

from scorer import ScoredLead


def _fmt_revenue(rev_millions: float) -> str:
    if rev_millions >= 1000:
        return f"${rev_millions / 1000:.1f}B"
    return f"${rev_millions:.0f}M"


def _tier_emoji(tier: str) -> str:
    return {"Tier 1": "🔴", "Tier 2": "🟡", "Watch List": "🟢", "Filtered Out": "⚪"}.get(tier, "")


def generate_markdown(leads: list[ScoredLead], run_date: datetime = None) -> str:
    if run_date is None:
        run_date = datetime.now(timezone.utc)

    date_str = run_date.strftime("%B %d, %Y")
    lines = [
        f"# L&Co — Business Development Pipeline",
        f"### Weekly Lead Scoring Report  |  {date_str}",
        "",
        "---",
        "",
    ]

    tier1 = [l for l in leads if l.tier == "Tier 1"]
    tier2 = [l for l in leads if l.tier == "Tier 2"]
    watch = [l for l in leads if l.tier == "Watch List"]

    def _write_tier(title: str, emoji: str, tier_leads: list[ScoredLead], lines=lines):
        lines.append(f"## {emoji} {title} ({len(tier_leads)} companies)")
        lines.append("")
        if not tier_leads:
            lines.append("_No leads in this tier this week._")
            lines.append("")
            return
        for lead in tier_leads:
            c = lead.company
            lines += [
                f"### {c.name}",
                f"**Score:** `{lead.score:.0f} / 100`  |  **Tier:** {lead.tier}",
                "",
                f"| Field | Detail |",
                f"|---|---|",
                f"| **HQ Location** | {c.hq_city}, {c.hq_state or c.hq_country} |",
                f"| **Annual Revenue** | {_fmt_revenue(c.annual_revenue_millions)} |",
                f"| **Industry** | {c.industry} |",
                f"| **Core Business** | {c.description[:120]}... |",
                f"| **Target Persona** | {lead.target_persona} |",
                "",
                f"**Why Now (Signal):**",
                f"> {lead.why_now}",
                "",
                f"**Score Breakdown:**",
                f"- Location: `{lead.breakdown.location_score:.0f}/25`",
                f"- Financial Fit: `{lead.breakdown.financial_score:.0f}/25`",
                f"- Partnership Signal: `{lead.breakdown.partnership_score:.0f}/30`",
                f"- Recency Trigger: `{lead.breakdown.recency_score:.0f}/20`",
                "",
            ]
            if c.known_partnerships:
                lines.append(f"**Known Partnerships:** {', '.join(c.known_partnerships[:4])}")
                lines.append("")
            if lead.candidate.triggering_articles:
                lines.append("**Triggering Articles This Week:**")
                for a in lead.candidate.triggering_articles[:3]:
                    pub = a.published.strftime("%b %d") if a.published else "n/d"
                    lines.append(f"- [{a.title[:90]}]({a.url}) — *{a.source}*, {pub}")
                lines.append("")
            lines.append("---")
            lines.append("")

    _write_tier("Tier 1 — High-Priority Outreach (Score > 80)", "🔴", tier1)
    _write_tier("Tier 2 — Active Pipeline (Score 60–80)", "🟡", tier2)
    _write_tier("Watch List (Score 40–60)", "🟢", watch)

    lines += [
        "## Pipeline Summary",
        "",
        f"| Tier | Count | Avg Score |",
        f"|---|---|---|",
        f"| Tier 1 | {len(tier1)} | {sum(l.score for l in tier1)/len(tier1):.1f} |" if tier1 else "| Tier 1 | 0 | — |",
        f"| Tier 2 | {len(tier2)} | {sum(l.score for l in tier2)/len(tier2):.1f} |" if tier2 else "| Tier 2 | 0 | — |",
        f"| Watch List | {len(watch)} | {sum(l.score for l in watch)/len(watch):.1f} |" if watch else "| Watch List | 0 | — |",
        "",
        f"_Generated by L&Co Business Development Pipeline — {date_str}_",
        "",
    ]

    return "\n".join(lines)


def generate_csv(leads: list[ScoredLead]) -> str:
    import io
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Company", "HQ City", "HQ State/Country", "Annual Revenue",
        "Industry", "Score", "Tier",
        "Location Score", "Financial Score", "Partnership Score", "Recency Score",
        "Why Now", "Target Persona", "Known Partnerships",
        "Triggering Article", "Article Source", "Article Date",
        "Website", "Stock Ticker",
    ])
    for lead in leads:
        c = lead.company
        art = lead.candidate.triggering_articles[0] if lead.candidate.triggering_articles else None
        writer.writerow([
            c.name,
            c.hq_city,
            c.hq_state or c.hq_country,
            _fmt_revenue(c.annual_revenue_millions),
            c.industry,
            f"{lead.score:.0f}",
            lead.tier,
            f"{lead.breakdown.location_score:.0f}",
            f"{lead.breakdown.financial_score:.0f}",
            f"{lead.breakdown.partnership_score:.0f}",
            f"{lead.breakdown.recency_score:.0f}",
            lead.why_now,
            lead.target_persona,
            "; ".join(c.known_partnerships[:3]),
            art.title if art else "",
            art.source if art else "",
            art.published.strftime("%Y-%m-%d") if art and art.published else "",
            c.website,
            c.stock_ticker,
        ])
    return output.getvalue()


def generate_json(leads: list[ScoredLead], run_date: datetime = None) -> str:
    if run_date is None:
        run_date = datetime.now(timezone.utc)

    records = []
    for lead in leads:
        c = lead.company
        articles = [
            {
                "title": a.title,
                "url": a.url,
                "source": a.source,
                "published": a.published.isoformat() if a.published else None,
            }
            for a in lead.candidate.triggering_articles
        ]
        records.append({
            "company": c.name,
            "hq": f"{c.hq_city}, {c.hq_state or c.hq_country}",
            "revenue": _fmt_revenue(c.annual_revenue_millions),
            "industry": c.industry,
            "score": lead.score,
            "tier": lead.tier,
            "score_breakdown": lead.breakdown.as_dict(),
            "why_now": lead.why_now,
            "target_persona": lead.target_persona,
            "known_partnerships": c.known_partnerships,
            "triggering_articles": articles,
            "website": c.website,
            "stock_ticker": c.stock_ticker,
        })

    return json.dumps({
        "run_date": run_date.isoformat(),
        "leads": records,
        "summary": {
            "tier1_count": sum(1 for l in leads if l.tier == "Tier 1"),
            "tier2_count": sum(1 for l in leads if l.tier == "Tier 2"),
            "watch_count": sum(1 for l in leads if l.tier == "Watch List"),
        }
    }, indent=2)


def save_reports(leads: list[ScoredLead], output_cfg: dict, run_date: datetime = None) -> dict[str, str]:
    if run_date is None:
        run_date = datetime.now(timezone.utc)

    reports_dir = Path(output_cfg["reports_dir"])
    reports_dir.mkdir(parents=True, exist_ok=True)

    date_slug = run_date.strftime("%Y-%m-%d")
    paths = {}

    if "markdown" in output_cfg["format"]:
        p = reports_dir / f"pipeline_{date_slug}.md"
        p.write_text(generate_markdown(leads, run_date), encoding="utf-8")
        paths["markdown"] = str(p)

    if "csv" in output_cfg["format"]:
        p = reports_dir / f"pipeline_{date_slug}.csv"
        p.write_text(generate_csv(leads), encoding="utf-8")
        paths["csv"] = str(p)

    if "json" in output_cfg["format"]:
        p = reports_dir / f"pipeline_{date_slug}.json"
        p.write_text(generate_json(leads, run_date), encoding="utf-8")
        paths["json"] = str(p)

    return paths
